"""Review Generator 配置 — 从统一配置继承"""

from litmind.config import (
    LLM_MODEL,
    REVIEW_MAX_PAPERS,
    REVIEW_MIN_THEMES,
    REVIEW_MAX_THEMES,
    REVIEW_CACHE_MAX_SIZE,
    REVIEW_CACHE_TTL,
    DISCUSSION_EVIDENCE_TOP_K,
)

REVIEW_MAX_PAPERS = REVIEW_MAX_PAPERS
REVIEW_MIN_THEMES = REVIEW_MIN_THEMES
REVIEW_MAX_THEMES = REVIEW_MAX_THEMES
CACHE_TTL_SECONDS = REVIEW_CACHE_TTL
CACHE_MAX_SIZE = REVIEW_CACHE_MAX_SIZE
COMPOSER_MODEL = LLM_MODEL
EVIDENCE_TOP_K = DISCUSSION_EVIDENCE_TOP_K
