"""Research Chat 配置 — 从统一配置继承"""

from litmind.config import (
    LLM_PROVIDER,
    LLM_MODEL,
    CACHE_TTL_SECONDS,
    CACHE_MAX_SIZE,
    CHAT_TOP_K,
)

DEFAULT_LLM_PROVIDER = LLM_PROVIDER
DEFAULT_LLM_MODEL = LLM_MODEL
CACHE_TTL_SECONDS = CACHE_TTL_SECONDS
CACHE_MAX_SIZE = CACHE_MAX_SIZE
DEFAULT_TOP_K = CHAT_TOP_K
