"""Evidence Finder 配置"""

# KB 查询
DEFAULT_TOP_K = 20
SEMANTIC_TOP_K = 15
LIKE_TOP_K = 20

# 证据强度阈值
STRONG_SUPPORT_MIN = 3       # 最少支持数
MODERATE_SUPPORT_RATIO = 2.0 # support/oppose 比
HIGH_SIMILARITY = 0.75       # 高相似度阈值
CONFIDENCE_WEIGHT_COUNT = 0.4
CONFIDENCE_WEIGHT_CONSISTENCY = 0.35
CONFIDENCE_WEIGHT_SIMILARITY = 0.25

# 缓存
CACHE_TTL_SECONDS = 300
CACHE_MAX_SIZE = 100

# 分类器
CLASSIFIER_MODEL = "claude-sonnet-4-20250514"
CLASSIFIER_BATCH_SIZE = 5     # 每批 LLM 分类的 claims 数
