"""Evidence Finder 配置 — 从统一配置继承"""

from litmind.config import (
    EV_DEFAULT_TOP_K,
    EV_SEMANTIC_TOP_K,
    EV_LIKE_TOP_K,
    EV_STRONG_SUPPORT_MIN,
    EV_MODERATE_SUPPORT_RATIO,
    EV_HIGH_SIMILARITY,
    EV_CONFIDENCE_WEIGHT_COUNT,
    EV_CONFIDENCE_WEIGHT_CONSISTENCY,
    EV_CONFIDENCE_WEIGHT_SIMILARITY,
    EV_CLASSIFIER_BATCH_SIZE,
    CACHE_TTL_SECONDS,
    CACHE_MAX_SIZE,
    LLM_MODEL,
)

# KB 查询
DEFAULT_TOP_K = EV_DEFAULT_TOP_K
SEMANTIC_TOP_K = EV_SEMANTIC_TOP_K
LIKE_TOP_K = EV_LIKE_TOP_K

# 证据强度阈值
STRONG_SUPPORT_MIN = EV_STRONG_SUPPORT_MIN
MODERATE_SUPPORT_RATIO = EV_MODERATE_SUPPORT_RATIO
HIGH_SIMILARITY = EV_HIGH_SIMILARITY
CONFIDENCE_WEIGHT_COUNT = EV_CONFIDENCE_WEIGHT_COUNT
CONFIDENCE_WEIGHT_CONSISTENCY = EV_CONFIDENCE_WEIGHT_CONSISTENCY
CONFIDENCE_WEIGHT_SIMILARITY = EV_CONFIDENCE_WEIGHT_SIMILARITY

# 缓存
CACHE_TTL_SECONDS = CACHE_TTL_SECONDS
CACHE_MAX_SIZE = CACHE_MAX_SIZE

# 分类器
CLASSIFIER_MODEL = LLM_MODEL
CLASSIFIER_BATCH_SIZE = EV_CLASSIFIER_BATCH_SIZE
