"""Discussion Generator 配置 — 从统一配置继承"""

from litmind.config import (
    LLM_MODEL,
    CACHE_TTL_SECONDS,
    DISCUSSION_EVIDENCE_TOP_K,
    DISCUSSION_MAX_RESULTS,
    DISCUSSION_CACHE_MAX_SIZE,
)

COMPOSER_MODEL = LLM_MODEL
EVIDENCE_TOP_K = DISCUSSION_EVIDENCE_TOP_K
CACHE_TTL_SECONDS = CACHE_TTL_SECONDS
CACHE_MAX_SIZE = DISCUSSION_CACHE_MAX_SIZE
MAX_RESULTS = DISCUSSION_MAX_RESULTS
